---
title: "Michigan Colors Demo"
author: "Andrew Grogan-Kaylor"
date: '`r format(Sys.Date(), format="%B %d, %Y")`'
output: 
  html_document: 
    fig_height: 4
    highlight: haddock
    number_sections: yes
    theme: default
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)

library(icon)

```

## Installation

You will need to install `devtools` if you have not already done so:

```{r, eval=FALSE}

install.packages("devtools")

```

Then use `devtools` to install `michigancolors`.

```{r, eval = FALSE}

devtools::install_github("agrogan1/michigancolors")

```

## Usage

```{r}

library(michigancolors)

```

## Allowable Colors

Allowable colors are: "blue", "maize", "tappan red", "ross school orange", "wave field green", "taubman teal", "arboretum blue", and "ann arbor amethyst"

## Help

```{r, eval = FALSE}

help(michigancolors)

```

## Examples

### Base R

```{r}

hist(iris$Petal.Length, col = michigancolors())

```

```{r}

hist(iris$Petal.Length, col = michigancolors("arboretum blue"))

```

```{r}

plot(iris$Petal.Length, 
     iris$Sepal.Length, 
     pch = 19,
     col = michigancolors("taubman teal"))

```

### ggplot2

```{r}

library(ggplot2)

```

```{r}

ggplot(iris, 
       aes(x = Petal.Length, 
           y = Sepal.Length, 
           color = Species)) + 
  geom_point() + 
  geom_smooth() + 
  ggtitle("Scatterplot of Iris Data Set") + 
  theme_minimal() + 
  scale_color_manual(values = michigancolors())


```





  
