---
title: "Colors in R"
description: |
  An R Color Chart
author:
  - name: Andy Grogan-Kaylor
    url: https://agrogan1.github.io/
    affiliation: University of Michigan
    affiliation_url: https://www.umich.edu
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    highlight: haddock
    toc: no
    fig_height: 6
  pdf_document: 
    fig_height: 3
    highlight: haddock
    latex_engine: xelatex
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

```

```{r}

library(ggplot2)

library(ggrepel)

library(dplyr)

```

```{r}


colornumber <- seq(1, 657, 1) # sequence of color numbers

colorname <- colors()[colornumber] # get color name associated with that number
  
colorname[colorname == "indianred"] <- NA
colorname[colorname == "indianred1"] <- NA
colorname[colorname == "indianred2"] <- NA
colorname[colorname == "indianred3"] <- NA
colorname[colorname == "indianred4"] <- NA

hexcode <- rgb(col2rgb(colorname)[1,], 
               col2rgb(colorname)[2,], 
               col2rgb(colorname)[3,], 
               max = 255) # hex code

hexcode <- factor(hexcode)

Rcolors <- data.frame(colornumber, colorname, hexcode)

# write.csv(Rcolors, file = "Rcolors.csv")

# DT::datatable(Rcolors)


```

```{r}

# from https://bookdown.org/yihui/rmarkdown-cookbook/font-color.html

colorize <- function(x, color) {
  
  if (knitr::is_latex_output()) {
  
      sprintf("\\textcolor{%s}{%s}", color, x)
  
  } else if (knitr::is_html_output()) {
    
    sprintf("<span style='background-color: %s;'>%s</span>", color, x)
    
  } else x
  
}

```

# Table of Colors

```{r, results='asis', eval=TRUE}

knitr::raw_html("<table>")

knitr::raw_html("<tr><td><b>hexcode</b></td><td><b>color name</b></td><td><b>color</b></td></tr>")

knitr::raw_html(paste("<tr><td>",
            hexcode, 
            "</td><td>",
            colorname,
            "</td><td>",
            colorize(Rcolors$colorname, Rcolors$hexcode),
            "</td></tr>"))

knitr::raw_html("</table>")

```

```{r, eval = FALSE}

# `r paste('red', 'FF0000', kableExtra::text_spec('red', background = 'red'))`

```

