---
title: "Colors in R"
subtitle: "An R Color Chart"
date: "today"
format:
  html:
    toc: true
    number-sections: true
    code-fold: true
    code-summary: "Show the code"
    theme:
      light: cosmo
      dark: vapor
---

# Call Libraries

```{r}
#| output: false

library(dplyr) # data wrangling

library(gt) # nifty tables

```

# Wrangle the Colors

```{r}

colornumber <- seq(1, 657, 1) # sequence of color numbers

colorname <- colors()[colornumber] # get color name associated with that number
  
hexcode <- rgb(col2rgb(colorname)[1,], 
               col2rgb(colorname)[2,], 
               col2rgb(colorname)[3,], 
               max = 255) # hex code

# hexcode <- factor(hexcode)

Rcolors <- data.frame(colornumber, colorname, hexcode)

# write.csv(Rcolors, file = "Rcolors.csv")

# DT::datatable(Rcolors)


```


```{r}
#| echo: false
#| eval: false

# from https://bookdown.org/yihui/rmarkdown-cookbook/font-color.html

colorize <- function(x, color) {
  
  if (knitr::is_latex_output()) {
  
      sprintf("\\textcolor{%s}{%s}", color, x)
  
  } else if (knitr::is_html_output()) {
    
    sprintf("<span style='background-color: %s;'>%s</span>", color, x)
    
  } else x
  
}

```

# Table of Colors

```{r}

gt::gt(Rcolors) %>% 
 cols_add(color = rep("  ", 657)) %>%
 tab_style(
    style = cell_fill(color = from_column(column = "hexcode")),
    locations = cells_body(columns = color)
  )     

```

```{r}
#| echo: false
#| eval: false
#| results: asis

knitr::raw_html("<table>")

knitr::raw_html("<tr><td><b>hexcode</b></td><td><b>color name</b></td><td><b>color</b></td></tr>")

knitr::raw_html(paste("<tr><td>",
            hexcode, 
            "</td><td>",
            colorname,
            "</td><td>",
            colorize(Rcolors$colorname, Rcolors$hexcode),
            "</td></tr>"))

knitr::raw_html("</table>")

```

```{r, eval = FALSE}

# `r paste('red', 'FF0000', kableExtra::text_spec('red', background = 'red'))`

```

